version: "3.9"

services:
  run:
    build:
      context: .
      dockerfile: Dockerfile
    image: "exercise-6"
    volumes:
      - .:/app
    working_dir: /app
    command: /spark/bin/spark-submit main.py

  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: "exercise-6"
    volumes:
      - .:/app
    working_dir: /app
    command: python3 -m pytest
